language: node_js
cache:
  npm: false
before_script:
  - npm install
script:
  - npm run lint && npm run test
after_success: npm run coverage
notifications:
  email:
    recipients:
      - llauromanuel@gmail.com
      - dylanalvarez1995@gmail.com
      - sebastian.e.blanco@gmail.com
deploy:
  provider: npm
  email: sebastian.e.blanco@gmail.com
  edge: true
  api_key:
    secure: 5606ee96-9a8c-4d95-bb21-316745a1a89c
  on:
    repo: fiuba-laboral-v2/validations
