language: node_js
cache:
  npm: false
before_script:
- npm install
script:
- npm run lint && npm run test
after_success: npm run coverage
notifications:
  email:
    recipients:
    - llauromanuel@gmail.com
    - dylanalvarez1995@gmail.com
    - sebastian.e.blanco@gmail.com
deploy:
  provider: npm
  email: sebastian.e.blanco@gmail.com
  edge: true
  api_key:
    secure: sJxCHJZou7cXajjywp6VtGhXivYjbY6s3IpB3VjpWReHPSXR/NDQkhphh6bd49Yw3mjWEKupZpnGgL2V1JoIMvgX+1h38klRQcwXUgNZKeg1Cy4P2CZ8JJnKQt9A4ieJhREq6/R9Gg2p1PP31ZNpXSeDVN3ITRpjSRVCGAGQ5oFefWj2hSRji/zdyKtCPi53MgYJW4qwIXfJTrLEvoS6AIGnJV8A5aIaKYHYlUO2DPdSDpq0nFjGTaI+ULdyYvDssLyTMfYSUNybfb6exxOHV3ymgRc68sXrRq5hXURKTdmOeehXuYk8ksg73iwHmvlWN9Q++dXLGLgyFT357flBNEHc6kYR6zO9SpS1lZOPrUTV0viqHWNl2ObrtiV5DUDTaPzJTjz6OExmYdaztcG8E215NU4MxGPFgny39hR6Tix5Wid+HSg/WATtBJ+3MoN0LNUYLHygxtWx6om9ftuj2LC+3/33e3vAD6cnzH6jXuuhtY6261EGWWdAKWzpwU+zujw/B2vPa86zTfHazAmUuXoZ3hPv6yz6jZ6HFx7s50S5SzBKneqwIpUeul0UlBoJ0oKiQTYMHV7j6ChQe3Eu0yEi3bpyrWks0TCzpxJbkfbvuuQFJc1VbZBOV/EZz5Cah0IXQMsuug+ej6WYpYgTmASsybRHmefLzdjTehNpLqI=
  on:
    repo: fiuba-laboral-v2/validations
